
///////////////
// 설비
////////////////
stream create --name "hvac" --definition "u2ware-bacnet-source  --remoteAddress=0.0.0.0:5121_2001,0.0.0.0:5122_2002,0.0.0.0:5123_2003,0.0.0.0:5124_2004,0.0.0.0:5125_2005,0.0.0.0:5126_2006,0.0.0.0:5127_2007,0.0.0.0:5128_2008,0.0.0.0:5129_2009,0.0.0.0:5130_2010,0.0.0.0:5131_2011,0.0.0.0:5132_2012,0.0.0.0:5133_2013,0.0.0.0:5134_2014  --remoteInstanceNumber=0  --localPort=47808 --fixedDelay=1000 | u2ware-data-mongodb-sink --host=127.0.0.1 --port=27017 --databaseName=hvac --idExpression=payload.id --valueExpression=payload.value" --deploy

///////////////
// 전력 
////////////////
stream create --name "electric" --definition "u2ware-bacnet-source  --remoteAddress=192.168.245.92:47808  --remoteInstanceNumber=4560  --localPort=47809 --fixedDelay=5000 | u2ware-data-mongodb-sink --host=127.0.0.1 --port=27017 --databaseName=electric --idExpression=payload.id --valueExpression=payload.value" --deploy

///////////////
// 조명 
////////////////
stream create --name "lighting" --definition "queue:fire > u2ware-netty-jungho-lighting-processor --host=192.168.245.3 --port=10808 | u2ware-data-mongodb-sink --host=127.0.0.1 --port=27017 --databaseName=lighting --idExpression=payload.id --valueExpression=payload.value --valueLogging=false"



///////////////
// REST 
////////////////
stream create --name "rest" --definition "u2ware-data-mongodb-rest --httpPort=9898 --host=127.0.0.1 --port=27017" --deploy
