stream create --name "spring-xd-u2ware-bacnet-source-mongodb-sink" --definition "u2ware-bacnet-source  --remoteAddress=127.0.0.1:47808  --remoteInstanceNumber=47808  --localPort=47812 --fixedDelay=5000 | u2ware-repository-mongodb-sink --host=127.0.0.1 --port=27017 --databaseName=bacnet --idExpression=payload.id --valueExpression=payload.value"

stream deploy --name "spring-xd-u2ware-bacnet-source-mongodb-sink"

stream create --name "spring-xd-u2ware-web-rest-mongodb-server" --definition "u2ware-web-rest-mongodb-server  --httpPort=9999 --httpTimeout=1000 --host=127.0.0.1 --port=27017"

stream deploy --name "spring-xd-u2ware-web-rest-mongodb-server"


http get --target http://localhost:9999/bacnet/bacnet

stream destroy --name "spring-xd-u2ware-bacnet-source-mongodb-sink"

stream destroy --name "spring-xd-u2ware-web-rest-mongodb-server"


15:50:42 [BACnet4J transport] INFO  i.g.u.i.bacnet.core.BacnetExecutor # iAmReceived [309] - iAmReceived: [instanceNumber=2400, address=192.168.245.91:47808
15:50:42 [BACnet4J transport] INFO  i.g.u.i.bacnet.core.BacnetExecutor # iAmReceived [309] - iAmReceived: [instanceNumber=2014, address=0.0.0.0:5134(2)
15:50:42 [BACnet4J transport] INFO  i.g.u.i.bacnet.core.BacnetExecutor # iAmReceived [309] - iAmReceived: [instanceNumber=2013, address=0.0.0.0:5133(2)
15:50:42 [BACnet4J transport] INFO  i.g.u.i.bacnet.core.BacnetExecutor # iAmReceived [309] - iAmReceived: [instanceNumber=2012, address=0.0.0.0:5132(2)
15:50:42 [BACnet4J transport] INFO  i.g.u.i.bacnet.core.BacnetExecutor # iAmReceived [309] - iAmReceived: [instanceNumber=2011, address=0.0.0.0:5131(2)
15:50:42 [BACnet4J transport] INFO  i.g.u.i.bacnet.core.BacnetExecutor # iAmReceived [309] - iAmReceived: [instanceNumber=2010, address=0.0.0.0:5130(2)
15:50:42 [BACnet4J transport] INFO  i.g.u.i.bacnet.core.BacnetExecutor # iAmReceived [309] - iAmReceived: [instanceNumber=2009, address=0.0.0.0:5129(2)
15:50:42 [BACnet4J transport] INFO  i.g.u.i.bacnet.core.BacnetExecutor # iAmReceived [309] - iAmReceived: [instanceNumber=2008, address=0.0.0.0:5128(2)
15:50:42 [BACnet4J transport] INFO  i.g.u.i.bacnet.core.BacnetExecutor # iAmReceived [309] - iAmReceived: [instanceNumber=2007, address=0.0.0.0:5127(2)
15:50:42 [BACnet4J transport] INFO  i.g.u.i.bacnet.core.BacnetExecutor # iAmReceived [309] - iAmReceived: [instanceNumber=2006, address=0.0.0.0:5126(2)
15:50:42 [BACnet4J transport] INFO  i.g.u.i.bacnet.core.BacnetExecutor # iAmReceived [309] - iAmReceived: [instanceNumber=2005, address=0.0.0.0:5125(2)
15:50:42 [BACnet4J transport] INFO  i.g.u.i.bacnet.core.BacnetExecutor # iAmReceived [309] - iAmReceived: [instanceNumber=2004, address=0.0.0.0:5124(2)
15:50:42 [BACnet4J transport] INFO  i.g.u.i.bacnet.core.BacnetExecutor # iAmReceived [309] - iAmReceived: [instanceNumber=2003, address=0.0.0.0:5123(2)
15:50:42 [BACnet4J transport] INFO  i.g.u.i.bacnet.core.BacnetExecutor # iAmReceived [309] - iAmReceived: [instanceNumber=2002, address=0.0.0.0:5122(2)
15:50:42 [BACnet4J transport] INFO  i.g.u.i.bacnet.core.BacnetExecutor # iAmReceived [309] - iAmReceived: [instanceNumber=2001, address=0.0.0.0:5121(2)
15:50:42 [BACnet4J transport] INFO  i.g.u.i.bacnet.core.BacnetExecutor # iAmReceived [309] - iAmReceived: [instanceNumber=4560, address=192.168.245.92:47808
15:50:45 [Thread-1] INFO  i.g.u.i.bacnet.core.BacnetExecutor # destroy [117] - BACNet Master Terminated Port Number: 47808
15:50:45 [Thread-1] INFO  i.g.u.i.bacnet.core.BacnetExecutor # shutdown [203] - Shutting down ExecutorService 'io.github.u2ware.integration.bacnet.core.BacnetExecutor#0'
