
stream create --name "testStream" --definition "queue:my > u2ware-netty-hyundai-elevator-processor --host=127.0.0.1 --port=10901 --idleTimeout=5000 | u2ware-data-mongodb-sink --host=127.0.0.1 --port=27017 --databaseName=elevator --idExpression=payload.id --valueExpression=payload.value --valueLogging=false"

stream deploy --name "testStream"

//stream undeploy --name "testStream"

//stream destroy --name "testStream"

