
stream create --name "testStream" --definition "queue:fire > u2ware-netty-jungho-lighting-processor --host=192.168.245.3 --port=10808 | u2ware-data-mongodb-sink --host=127.0.0.1 --port=27017 --databaseName=lighting --idExpression=payload.id --valueExpression=payload.value --valueLogging=false"

stream deploy --name "testStream"

//stream undeploy --name "testStream"

//stream destroy --name "testStream"

