
stream create --name "testStream" --definition "u2ware-modbus-source --host=127.0.0.1 --port=10502 --unitId=0 --functionCode=4 --offset=0 --count=6 --fixedDelay=5000 | u2ware-ibs-data-mongodb-sink --host=127.0.0.1 --port=27017 --databaseName=modbus --idExpression=payload.id --valueExpression=payload.value"

stream deploy --name "testStream"

//stream undeploy --name "testStream"

//stream destroy --name "testStream"
